name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build & push the Docker image
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        PASS_SALT_LENGTH: ${{ secrets.PASS_SALT_LENGTH }}
        PASS_HASH_LENGTH: ${{ secrets.PASS_HASH_LENGTH }}
        PASS_HASH_ALGORITHM: ${{ secrets.PASS_HASH_ALGORITHM }}
        PASS_HASH_ITERATIONS: ${{ secrets.PASS_HASH_ITERATIONS }}
        JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
        TOKEN_LIFETIME: ${{ secrets.TOKEN_LIFETIME }}
        AUTH_TEST_PASS_HASH: ${{ secrets.AUTH_TEST_PASS_HASH }}
        AUTH_TEST_PASS_SALT: ${{ secrets.AUTH_TEST_PASS_SALT }}
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: kainos-job-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --build-arg DB_PASSWORD=${DB_PASSWORD} \
        --build-arg DB_USERNAME=${DB_USERNAME} \
        --build-arg DB_HOST=${DB_HOST} \
        --build-arg DB_NAME=${DB_NAME} \
        --build-arg PASS_SALT_LENGTH=${PASS_SALT_LENGTH} \
        --build-arg PASS_HASH_LENGTH=${PASS_HASH_LENGTH} \
        --build-arg PASS_HASH_ALGORITHM=${PASS_HASH_ALGORITHM} \
        --build-arg PASS_HASH_ITERATIONS=${PASS_HASH_ITERATIONS} \
        --build-arg JWT_ISSUER=${JWT_ISSUER} \
        --build-arg TOKEN_LIFETIME=${TOKEN_LIFETIME} \
        --build-arg AUTH_TEST_PASS_HASH=${AUTH_TEST_PASS_HASH} \
        --build-arg AUTH_TEST_PASS_SALT=${AUTH_TEST_PASS_SALT} \
        --build-arg TEST_USER_EMAIL=${TEST_USER_EMAIL} \
        --build-arg TEST_USER_PASSWORD=${TEST_USER_PASSWORD} \
        -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG